### ISSUE TITLE
Documentation Notes

### ISSUE THREAD

**Issue by esdev** [norcross/gf-tooltips#1]
Great plugin. Works fantastic.

You might mention in the Readme that the plugin does not work when previewing the form. It must be placed on an actual page for it to work.

Had me stumped for a few minutes.

**Comment by norcross** [comment]
gotcha. I think this weekend I'm going to polish it a bit (there are some quirks with where the tooltip appears depending on where your labels are located) and the 'officially' release it.

**Comment by esdev** [comment]
Sounds great. I look forward to it. Your plugin came right when I needed it. Thanks for the great work again.

**Comment by jjstevens17** [comment]
Hi!  This plugin came in super handy on a project I'm working on but the tooltips seemed to have died on a multi-part form utilizing AJAX.  They appear on the first page but on subsequent pages the tooltips just appear as a description under the label.  Would be great if this could be made to work with Ajaxy, Multi-part forms! 
- Thanks, John

**Comment by pubterrance** [comment]
Hi, I've chosen the option to manually add tooltips, however when I go to my form I don't see how to make this happen. Has anyone else experienced this? Thanks.

**Comment by leowebguy** [comment]
@pubterrance you have to add "gf-tooltip-manual" class to each appropriate field.
