### ISSUE TITLE
Wordpress 4.1 compatibility

### ISSUE THREAD

**Issue by nwbermudez** [norcross/gf-tooltips#14]
Are you going to make the wordpress tooltip compatible with Wordpress 4.0... please!

**Comment by norcross** [comment]
wasn't aware that it wasn't. what's the error?

**Comment by nwbermudez** [comment]
I activated it.  When I click on settings nothing happens. 

I downloaded the latest version?!?!? From github after a search of Google.  Not sure why it didn't load.

A lot of plugins have been having problems with 4.0.  They did a few things differently I think.  Gravity form just released an update too.  Could be a hook issue.  Not sure myself, I'm more of a designer than a programer.

Nicholas W. Bermudez
773.517.9242

**Comment by norcross** [comment]
I just looked, this is an old and unsupported version. I've made a new version that is linked in the readme file.
