### ISSUE TITLE
Internet Explorer issue

### ISSUE THREAD

**Issue by Letability** [norcross/gf-tooltips#3]
Hello,

Great plugin but I have one issue.

It works great in Firefox and Chrome but, using the default selection, the form does not appear in IE.

However, through a process of elimination, I have found that if I select 'display on field label hover' for the Tooltip Layout as opposed to the default 'insert tooltip icon next to label' it works perfectly! 

I am using IE 9 on this machine but I have also tested it using IE8 on another machine and I get the same problem.

Can you help?

Many thanks,

Peter.

**Comment by norcross** [comment]
I'll see what I can do.

**Comment by cglusky** [comment]
Any luck with this one?  Going to start building a store that requires some help with attributes and your tooltips should work great.  Can help test.
Thanks!
Coby

**Comment by norcross** [comment]
not yet. I honestly got sidetracked and forgot to look at it. I'll see what I can do.

**Comment by norcross** [comment]
ok. the issue is that IE8 doesn't like an inline-block element inside a label, which is how the icon is being loaded. I'm working on a fix.

@Letability I tested, and IE9 is fine. if the form itself isn't loading, that's another issue all together.

**Comment by norcross** [comment]
I've just updated the repo. refactored how the icons are loaded, should take care of the issue.

**Comment by cglusky** [comment]
Nice work; thanks!  Should get to test this over the next few weeks.
