### ISSUE TITLE
Displaying tooltip at input / textarea instead of label

### ISSUE THREAD

**Issue by xcellenceit** [norcross/gf-tooltips#4]
Hi, 

Its a great plugin that works really well. Thank you.

I've applied it to label, as icon doesn't fit properly into the design... However visitor doesn't get a clue that there is a tooltip when they hover on the label... so I think its great if we can change it to display tooltip when he is hovering on the input or actually typing into input / text area.

Any idea how can we display tooltip on input/text area instead of the label. 

Any help is appreciated.

Thank you

**Comment by norcross** [comment]
offhand it would be a matter of targeting the different area. but from a UI perspective having things pop up / change while entering text would be a pain for the user.

you can also use the icon type and tweak the CSS to fit your liking.

**Comment by xcellenceit** [comment]
Can you give me an idea what changes I should be making and where?

**Comment by norcross** [comment]
if you look in the `gf-tooltips.js` file, you'll see how it's being called based on the options in the plugin and where it's applied (label or icon). change the call there, or add your own.

**Comment by xcellenceit** [comment]
Okay. Thank you for your support. We'll try that.
